[project]
name = "myswisscloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "selenium>=4.38.0",
    "selenium-wire>=5.1.0",
    "webdriver-manager>=4.0.2",
]
